# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-graph:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
         matrix:
           python-version: [3.7,]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
    - uses: actions/checkout@v2
      with:
        submodules: recursive           
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        pip install pydot
        python -m pip install --upgrade pip
        pip install pydot        
        pip install click 
        pip install pydot
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Delete older graph
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        rm graph.png
        git status
        git add 'graph.png'
        git commit -m "deleted older graph"
        
    - name: Create Graph and push it to repo
      run: |
        python submodule.py -m png ../GW-Releases
        git status
        git add 'graph.png'
        git commit -m "Updates graph"
        git push
        

