# This is a basic workflow to help you get started with Actions

name: visualization

# Controls when the action will run. 
on:
  push:
  # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag
       
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-graph:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it  
    - uses: actions/checkout@v2
      with:
        repository: k8-proxy/GW-Releases
        token: ${{secrets.GITHUBPAT}}
        submodules: recursive           
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        pip install pydot    
        pip install click 
        pip install requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Update graph
      run: |
        git config user.name github-actions@github.com
        git config user.email github-actions
        BRANCH_NAME=visualization-${GITHUB_SHA::7}
        git remote -v
        git checkout -b $BRANCH_NAME
        
        # delete older graph
        rm graph.png
        git add 'graph.png'
        git commit -m "deleted older graph"

        python scripts/submodule_visualization.py ../GW-Releases
        
        # add new graph
        git status
        git add 'graph.png'
        git commit -m "Updates new graph"
        git push -u origin $BRANCH_NAME
        
        # create a pull request from a new branch to target branch, merge the PR and delete the source branch.
        gh pr create --title "Update visualization for new tag" --body ""
        sleep 5s
        gh pr merge $BRANCH_NAME -s -d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBPAT }}
